task:
  name: "classification"
  type: "CDDG"
  loss: "CE"
  metrics:
    - "acc"

  # CDDG 划分参数（参考旧 demo 配置）
  target_system_id: [1]
  target_domain_num: 1

  optimizer: "adam"
  batch_size: 32
  num_workers: 4
  pin_memory: true
  shuffle: true
  log_interval: 10
  epochs: 10
  lr: 0.001
  weight_decay: 0.0001
