environment:
  WANDB_MODE: "disabled"
  VBENCH_HOME: "/path/to/Vbench"
  project: "pretrain_demo"
  seed: 0
  iterations: 1

data:
  data_dir: "/path/to/data"
  metadata_file: "metadata.csv"
  batch_size: 32
  num_workers: 4
  window_size: 1024
  stride: 5
  num_window: 32

model:
  name: "Transformer_Dummy"
  type: "Transformer"
  input_dim: 2
  num_classes: 4

task:
  name: "Classification"
  type: "Pretraining"
  pred_len: 1
  loss: "MSE"
  lr: 0.001

trainer:
  name: "Default_trainer"
  num_epochs: 1
  gpus: 1
  device: 'cuda'
